var { aptoide, aptoidedl, aptoideSearch, characterAi, danbooru, fbdl, kwaidl, GDriveDl, igdl, igstalk, mediafireV2, Nationality, openAi, ChatGpt, ChatGptV2, tiktokdl, tiktokdlV2, tiktokuser, tiktokvid, tiktokStalk, tiktokSearch, pinterest, pinterestdl, ppcouple, spotifySearch, spotify, spotifydl, xnxxdl, xvideosdl, ytsearch, ytmp3, ytmp4 } = require("./starlights")

module.exports = {
    aptoide: aptoide,
    aptoidedl: aptoidedl,
    aptoideSearch: aptoideSearch,
    characterAi: characterAi,
    danbooru: danbooru,
    fbdl: fbdl,
    kwaidl: kwaidl,
    GDriveDl: GDriveDl,
    igdl: igdl,
    igstalk: igstalk,
    mediafireV2: mediafireV2,
    Nationality: Nationality,
    openAi: openAi,
    ChatGpt: ChatGpt,
    ChatGptV2: ChatGptV2,
    spotifySearch: spotifySearch,
    spotify: spotify,
    spotifydl: spotifydl,
    tiktokdl: tiktokdl,
    tiktokdlV2: tiktokdlV2,
    tiktokuser: tiktokuser,
    tiktokStalk: tiktokStalk,
    tiktokvid: tiktokvid,
    tiktokSearch: tiktokSearch,
    pinterest: pinterest,
    pinterestdl: pinterestdl,
    ppcouple: ppcouple,
    xnxxdl: xnxxdl,
    xvideosdl: xvideosdl,
    ytsearch: ytsearch,
    ytmp3: ytmp3,
    ytmp4: ytmp4
}